### ISSUE TITLE
Create "Blog" Tab and display Blog page

### ISSUE THREAD

**Issue by membriux** [membriux/VidaNueva#3]
- [x] Create a new tab on top for the menu called "Blog" like the image:
- [x] User clicks on Blog it should take you to a new page, just have it say something like "Hello World" for now

![Image](https://github.com/user-attachments/assets/616c75db-4b6a-46a0-bdce-865e07ff7308)

**Comment by MCdev92** [comment]
Done:


![Image](https://github.com/user-attachments/assets/f9db9a21-eadd-411f-9bad-54694624e693)


route:
![Image](https://github.com/user-attachments/assets/a0223c31-7d0f-4bb5-abbe-3d1ddc9c0692)
