### ISSUE TITLE
Fetch Sample Blog content from Back4app database

### ISSUE THREAD

**Issue by membriux** [membriux/VidaNueva#4]
- [x] Add 3 sample blog data directly on database
- [x] On the "Blog" page, fetch/read data from Back4app - Blogs collection
  - here is the documentation: https://www.back4app.com/docs/get-started/read-and-write-data
- [x] Display each title of the blogs on the page

ONLY READ data for now

**Comment by MCdev92** [comment]
webpage:


![Image](https://github.com/user-attachments/assets/7ab3fd91-b985-4aff-bf61-42da23aa451e)

Database: 


![Image](https://github.com/user-attachments/assets/ec4aff0f-5913-4624-bc3a-314c4b004584)
