### ISSUE TITLE
Add Header and Footer template to Blog page

### ISSUE THREAD

**Issue by membriux** [membriux/VidaNueva#5]
Make sure that when you go to "Blog" page, it shows the header and footer template that already exist. 
For example, when you click on any other menu item (example: varones page) it always has the header and footer as shown on the picture below:

![Image](https://github.com/user-attachments/assets/23890bf0-ad24-4fac-8c28-0cf0ed81c4e4)

**Comment by MCdev92** [comment]
Perfect:


![Image](https://github.com/user-attachments/assets/68d8468f-d239-488c-a028-e0e20455eb05)
