### ISSUE TITLE
Blogs List Page: Bootstrap Cards Integration

### ISSUE THREAD

**Issue by membriux** [membriux/VidaNueva#7]
Please include a GIF showing how it works in both Desktop + Mobile

- [ ] Integrate cards for each blog post instead of a table. Documentations:
  - https://www.w3schools.com/bootstrap4/bootstrap_cards.asp
  - https://getbootstrap.com/docs/4.0/components/card/
- [ ] There should be 3 - 4 blog cards
  - [ ] If viewing on mobile, it should be one card 

There is an example on the main page. Look at the "Leer Mas" section on the home page:

![Image](https://github.com/user-attachments/assets/b812ad6c-ad23-40a7-b5d7-27105dc68fbe)

**Comment by MCdev92** [comment]
I changed my router because I was not able to fetch images from back4App so I hardcoded my blog router. It works. 
![Image](https://github.com/user-attachments/assets/b2e07304-ee46-4a89-8594-bd7e67b99a4d)
