### ISSUE TITLE
Blog Details Page -  View

### ISSUE THREAD

**Issue by membriux** [membriux/VidaNueva#8]
When a user clicks on a Blog card, it should take them to the Full blog page.
A full blog should look something like /beca page.

Here, you will need to add a dynamic endpoint for each blog.
Here is how you would do it:

- Create a dynamic endpoint for Blog details page
  - something like `router.get(blogs/:blog_id) .....`  inside of `routes/blogs.js`. [Google Search to help you find it](https://www.google.com/search?q=express+js+dynamic+route&oq=express+js+dynamic+route&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBCDYyMDdqMGo0qAIAsAIB&sourceid=chrome&ie=UTF-8)
- When clicking on a blog, you pass the blog object from the Blog array of objects to the details page
- Render the Blog in the page (i.e. Title, Subtitle, Author, Create/Update Date, Membership, blog_content/details)

**Comment by MCdev92** [comment]
Visual proof:
![Image](https://github.com/user-attachments/assets/96e8fe62-51a1-4d75-a312-31ee64288973)
