### ISSUE TITLE
Blog Details Page - Render Markdown for Blog content

### ISSUE THREAD

**Issue by membriux** [membriux/VidaNueva#9]
When viewing a blog, it should render the `markdown` content. 

Here is a google search to help you get started: 
- [Google Search](https://www.google.com/search?q=node+js+express+render+markdown&sca_esv=449428b1edf18ef7&sxsrf=ADLYWILA2qRwlu8rrxXbOyZ46HgoN3K3aw%3A1725860229369&source=hp&ei=hYneZu72E_bnkPIPh7HXyQI&iflsig=AL9hbdgAAAAAZt6XlSe42V58pW3m55-dqf5V_BegfOUL&ved=0ahUKEwiuzZqvkrWIAxX2M0QIHYfYNSkQ4dUDCBk&uact=5&oq=node+js+express+render+markdown&gs_lp=Egdnd3Mtd2l6Ih9ub2RlIGpzIGV4cHJlc3MgcmVuZGVyIG1hcmtkb3duMgUQIRigATIFECEYoAEyBRAhGKABMgUQIRigATIFECEYqwIyBRAhGJ8FSJdGUABY6URwAHgAkAEAmAFroAGjFaoBBDI2LjW4AQPIAQD4AQGYAh-gAoYWwgIKECMYgAQYJxiKBcICBBAjGCfCAgoQABiABBhDGIoFwgILEAAYgAQYkQIYigXCAgsQLhiABBixAxiDAcICDhAAGIAEGLEDGIMBGIoFwgILEAAYgAQYsQMYgwHCAhAQLhiABBjRAxhDGMcBGIoFwgINEAAYgAQYsQMYQxiKBcICEBAAGIAEGLEDGEMYgwEYigXCAg4QABiABBiRAhixAxiKBcICEBAAGIAEGLEDGIMBGBQYhwLCAhEQABiABBiRAhixAxiDARiKBcICBRAAGIAEwgIKEAAYgAQYFBiHAsICBhAAGBYYHsICCBAAGBYYHhgPwgILEAAYgAQYhgMYigXCAggQABiABBiiBMICCBAAGKIEGIkFmAMAkgcEMjIuOaAHxbUB&sclient=gws-wiz)
- [Google Search 2](https://www.google.com/search?q=express+js+render+markdown+to+html&sca_esv=449428b1edf18ef7&sxsrf=ADLYWIIX-xe_uVP29hsLB7lbkrW-xPexWA%3A1725860397793&ei=LYreZumWMJDfkPIPwJGt-Qg&ved=0ahUKEwip4cT_krWIAxWQL0QIHcBIK48Q4dUDCBE&uact=5&oq=express+js+render+markdown+to+html&gs_lp=Egxnd3Mtd2l6LXNlcnAiImV4cHJlc3MganMgcmVuZGVyIG1hcmtkb3duIHRvIGh0bWwyBhAAGBYYHjIIEAAYgAQYogQyCBAAGIAEGKIEMggQABiABBiiBDIIEAAYgAQYogRI9VxQnxJYwltwBXgBkAEAmAGBAaABqxyqAQUyOS4xMLgBA8gBAPgBAZgCLKACrh2oAhDCAgoQABiwAxjWBBhHwgIHECMYJxjqAsICFBAAGIAEGOMEGLQCGOkEGOoC2AEBwgILEAAYgAQYkQIYigXCAgoQABiABBhDGIoFwgIREC4YgAQYsQMY0QMYgwEYxwHCAg4QABiABBixAxiDARiKBcICCxAAGIAEGLEDGIMBwgIOEC4YgAQYsQMY0QMYxwHCAgQQIxgnwgINEAAYgAQYsQMYFBiHAsICExAuGIAEGLEDGNEDGEMYxwEYigXCAhAQABiABBixAxhDGIMBGIoFwgIFEAAYgATCAgsQABiABBiGAxiKBcICBRAhGKABwgIFECEYqwLCAgUQIRifBZgDCYgGAZAGCLoGBggBEAEYAZIHBTMwLjE0oAeZlgI&sclient=gws-wiz-serp)

**Comment by MCdev92** [comment]
![Image](https://github.com/user-attachments/assets/dd694d0a-56ed-4bb5-af62-28e7fc710c8d)
